version: '3.8'

services:
  web:
    image: smart_soft_system:latest
    container_name: smart_soft_system
    ports:
      - "5051:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    labels:
      - "com.smart-soft-system.description=Smart Soft System Landing Page"
